apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dublancer-enterprise
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: dublancer-enterprise
      app.kubernetes.io/component: web
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-system
      ports:
        - protocol: TCP
          port: 3000
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
    - ports:
        - { protocol: TCP, port: 443 }
        - { protocol: TCP, port: 5432 }
        - { protocol: TCP, port: 6379 }
        - { protocol: TCP, port: 4318 }
