import { z } from "zod";

const id = z.string().min(8).max(128);
const shortText = z.string().trim().min(1).max(255);
const longText = z.string().trim().min(1).max(50_000);
const optionalText = z.string().trim().max(2_000).optional();
const money = z.coerce.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const percentage = z.coerce.number().int().min(0).max(100);
const isoDate = z.iso.datetime();
const metadata = z.record(z.string(), z.unknown()).optional();

export const crmActionSchema = z.discriminatedUnion("action", [
  z.object({
    action: z.literal("pipeline.create"),
    name: shortText,
    description: optionalText,
    isDefault: z.boolean().default(false),
    stages: z.array(z.object({
      name: shortText,
      probability: percentage,
      category: z.enum(["OPEN", "WON", "LOST"]).default("OPEN"),
    })).min(2).max(20),
  }),
  z.object({
    action: z.literal("lead.create"),
    firstName: shortText,
    lastName: shortText,
    email: z.email().optional(),
    phone: z.string().trim().max(50).optional(),
    companyName: optionalText,
    jobTitle: optionalText,
    source: optionalText,
    score: z.coerce.number().int().min(0).max(100).default(0),
    assignedToMembershipId: id.optional(),
    metadata,
  }),
  z.object({
    action: z.literal("lead.convert"),
    leadId: id,
    accountName: shortText,
    opportunityName: shortText,
    pipelineId: id,
    stageId: id,
    amountMinor: money,
    currency: z.string().trim().length(3).default("AED"),
  }),
  z.object({
    action: z.literal("account.create"),
    name: shortText,
    industry: optionalText,
    website: z.url().optional(),
    phone: z.string().trim().max(50).optional(),
    countryCode: z.string().trim().length(2).default("AE"),
    ownerMembershipId: id.optional(),
    parentAccountId: id.optional(),
    metadata,
  }),
  z.object({
    action: z.literal("contact.create"),
    accountId: id,
    firstName: shortText,
    lastName: shortText,
    email: z.email().optional(),
    phone: z.string().trim().max(50).optional(),
    jobTitle: optionalText,
    ownerMembershipId: id.optional(),
    isPrimary: z.boolean().default(false),
    metadata,
  }),
  z.object({
    action: z.literal("opportunity.create"),
    accountId: id,
    primaryContactId: id.optional(),
    pipelineId: id,
    stageId: id,
    ownerMembershipId: id.optional(),
    name: shortText,
    amountMinor: money,
    currency: z.string().trim().length(3).default("AED"),
    expectedCloseAt: isoDate.optional(),
    metadata,
  }),
  z.object({
    action: z.literal("opportunity.advance"),
    opportunityId: id,
    stageId: id,
    expectedVersion: z.coerce.number().int().positive(),
    lostReason: optionalText,
  }),
  z.object({
    action: z.literal("activity.create"),
    type: z.enum(["CALL", "EMAIL", "MEETING", "TASK", "NOTE", "SYSTEM"]),
    subject: shortText,
    details: optionalText,
    accountId: id.optional(),
    contactId: id.optional(),
    opportunityId: id.optional(),
    leadId: id.optional(),
    dueAt: isoDate.optional(),
    occurredAt: isoDate.optional(),
    metadata,
  }),
  z.object({
    action: z.literal("note.create"),
    body: longText,
    isPinned: z.boolean().default(false),
    accountId: id.optional(),
    contactId: id.optional(),
    opportunityId: id.optional(),
    leadId: id.optional(),
  }),
  z.object({
    action: z.literal("quote.create"),
    opportunityId: id,
    contactId: id.optional(),
    currency: z.string().trim().length(3).default("AED"),
    discountMinor: money.default(0),
    taxMinor: money.default(0),
    validUntil: isoDate.optional(),
    terms: optionalText,
    lines: z.array(z.object({
      description: shortText,
      quantity: z.coerce.number().int().positive().max(100_000),
      unitPriceMinor: money,
      metadata,
    })).min(1).max(200),
  }),
  z.object({
    action: z.literal("quote.transition"),
    quoteId: id,
    status: z.enum(["SENT", "ACCEPTED", "REJECTED", "EXPIRED"]),
    expectedVersion: z.coerce.number().int().positive(),
  }),
  z.object({
    action: z.literal("health.capture"),
    accountId: id,
    score: z.coerce.number().int().min(0).max(100),
    signals: z.record(z.string(), z.unknown()),
    source: shortText.default("RULE_ENGINE"),
  }),
  z.object({
    action: z.literal("metric.record"),
    accountId: id,
    key: z.string().trim().min(1).max(100),
    value: z.coerce.number().finite(),
    periodStart: isoDate,
    periodEnd: isoDate,
    metadata,
  }),
]);

export const talentActionSchema = z.discriminatedUnion("action", [
  z.object({
    action: z.literal("profile.upsert"),
    membershipId: id,
    title: shortText,
    summary: optionalText,
    status: z.enum(["ACTIVE", "ON_LEAVE", "INACTIVE"]).default("ACTIVE"),
    location: optionalText,
    timezone: shortText.default("Asia/Dubai"),
    hireDate: isoDate.optional(),
    costRateMinor: money.optional(),
    billRateMinor: money.optional(),
    currency: z.string().trim().length(3).default("AED"),
    targetUtilizationPercent: percentage.default(80),
  }),
  z.object({
    action: z.literal("skill.upsert"),
    talentProfileId: id,
    skillId: id,
    proficiency: z.enum(["FOUNDATION", "INTERMEDIATE", "ADVANCED", "EXPERT"]),
    yearsExperience: z.coerce.number().int().min(0).max(80).default(0),
    verified: z.boolean().default(false),
  }),
  z.object({
    action: z.literal("certification.create"),
    talentProfileId: id,
    name: shortText,
    issuer: shortText,
    credentialId: optionalText,
    credentialUrl: z.url().optional(),
    issuedAt: isoDate,
    expiresAt: isoDate.optional(),
  }),
  z.object({
    action: z.literal("availability.create"),
    talentProfileId: id,
    status: z.enum(["AVAILABLE", "PARTIAL", "UNAVAILABLE"]),
    startsAt: isoDate,
    endsAt: isoDate,
    capacityPercent: percentage,
    reason: optionalText,
  }),
  z.object({
    action: z.literal("plan.create"),
    name: shortText,
    description: optionalText,
    projectId: id.optional(),
    startsAt: isoDate,
    endsAt: isoDate,
    budgetHours: z.coerce.number().int().positive().optional(),
    activate: z.boolean().default(false),
  }),
  z.object({
    action: z.literal("requirement.create"),
    resourcePlanId: id,
    skillId: id.optional(),
    roleTitle: shortText,
    requiredProfiles: z.coerce.number().int().positive().max(1_000).default(1),
    hoursPerWeek: z.coerce.number().int().positive().max(168).default(40),
    minProficiency: z.enum(["FOUNDATION", "INTERMEDIATE", "ADVANCED", "EXPERT"]).optional(),
    startsAt: isoDate,
    endsAt: isoDate,
  }),
  z.object({
    action: z.literal("staffing.assign"),
    resourcePlanId: id,
    requirementId: id.optional(),
    talentProfileId: id,
    projectId: id.optional(),
    allocationPercent: percentage,
    hoursPerWeek: z.coerce.number().int().positive().max(168),
    startsAt: isoDate,
    endsAt: isoDate,
    activate: z.boolean().default(true),
  }),
  z.object({
    action: z.literal("capacity.capture"),
    talentProfileId: id,
    periodStart: isoDate,
    periodEnd: isoDate,
    availableHours: z.coerce.number().int().nonnegative(),
    allocatedHours: z.coerce.number().int().nonnegative(),
  }),
  z.object({
    action: z.literal("bench.enter"),
    talentProfileId: id,
    reason: optionalText,
    nextAssignmentDate: isoDate.optional(),
  }),
  z.object({
    action: z.literal("bench.exit"),
    benchEntryId: id,
    status: z.enum(["PARTIALLY_ALLOCATED", "ASSIGNED", "EXITED"]),
  }),
  z.object({
    action: z.literal("performance.record"),
    talentProfileId: id,
    periodStart: isoDate,
    periodEnd: isoDate,
    rating: z.enum(["BELOW_EXPECTATIONS", "MEETS_EXPECTATIONS", "EXCEEDS_EXPECTATIONS", "EXCEPTIONAL"]),
    utilizationPercent: percentage.optional(),
    deliveryScore: percentage.optional(),
    feedback: optionalText,
    goals: z.record(z.string(), z.unknown()).optional(),
  }),
]);

export const knowledgeActionSchema = z.discriminatedUnion("action", [
  z.object({
    action: z.literal("category.create"),
    name: shortText,
    slug: z.string().trim().min(2).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    description: optionalText,
    parentId: id.optional(),
  }),
  z.object({
    action: z.literal("article.create"),
    categoryId: id.optional(),
    slug: z.string().trim().min(2).max(140).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    title: shortText,
    summary: optionalText,
    locale: z.enum(["en-AE", "ar-AE"]).default("en-AE"),
    body: longText,
    isInternal: z.boolean().default(true),
    metadata,
  }),
  z.object({
    action: z.literal("article.version.create"),
    articleId: id,
    title: shortText,
    body: longText,
    changeSummary: optionalText,
  }),
  z.object({
    action: z.literal("article.submit"),
    articleId: id,
    reviewerIds: z.array(id).min(1).max(20),
  }),
  z.object({
    action: z.literal("approval.decide"),
    approvalId: id,
    decision: z.enum(["APPROVED", "CHANGES_REQUESTED", "REJECTED"]),
    comment: optionalText,
  }),
  z.object({
    action: z.literal("article.publish"),
    articleId: id,
  }),
  z.object({
    action: z.literal("article.archive"),
    articleId: id,
  }),
  z.object({
    action: z.literal("faq.upsert"),
    faqId: id.optional(),
    categoryId: id.optional(),
    question: shortText,
    answer: longText,
    locale: z.enum(["en-AE", "ar-AE"]).default("en-AE"),
    publish: z.boolean().default(false),
    sortOrder: z.coerce.number().int().min(0).max(100_000).default(0),
  }),
]);

export const knowledgeRetrievalSchema = z.object({
  query: z.string().trim().min(2).max(1_000),
  locale: z.enum(["en-AE", "ar-AE"]).optional(),
  take: z.coerce.number().int().min(1).max(10).default(5),
  aiAssist: z.boolean().default(false),
  idempotencyKey: z.string().trim().min(8).max(200).optional(),
});

export const integrationActionSchema = z.discriminatedUnion("action", [
  z.object({
    action: z.literal("connector.create"),
    name: shortText,
    key: z.string().trim().min(2).max(100).regex(/^[a-z0-9]+(?:[._-][a-z0-9]+)*$/),
    type: z.enum(["REST", "IMPORT", "EXPORT"]),
    baseUrl: z.url(),
    method: z.enum(["GET", "POST", "PUT", "PATCH"]).default("POST"),
    path: z.string().trim().startsWith("/").max(500).default("/"),
    authType: z.enum(["NONE", "API_KEY", "BEARER", "BASIC", "OAUTH2"]).default("NONE"),
    authConfig: z.record(z.string(), z.string()).optional(),
    defaultHeaders: z.record(z.string(), z.string()).optional(),
    requestTimeoutMs: z.coerce.number().int().min(500).max(60_000).default(15_000),
    maxAttempts: z.coerce.number().int().min(1).max(10).default(5),
    mapping: z.record(z.string(), z.unknown()).optional(),
    activate: z.boolean().default(true),
  }),
  z.object({
    action: z.literal("apiKey.create"),
    name: shortText,
    scopes: z.array(z.enum(["events.publish", "connectors.execute", "monitoring.read"])).min(1),
    expiresAt: isoDate.optional(),
  }),
  z.object({
    action: z.literal("apiKey.revoke"),
    apiKeyId: id,
  }),
  z.object({
    action: z.literal("oauth.upsert"),
    oauthId: id.optional(),
    connectorId: id.optional(),
    provider: shortText,
    name: shortText,
    clientId: shortText,
    clientSecret: z.string().min(8).max(5_000).optional(),
    authorizationUrl: z.url().optional(),
    tokenUrl: z.url().optional(),
    scopes: z.array(shortText).max(100).default([]),
    accessToken: z.string().min(8).max(20_000).optional(),
    refreshToken: z.string().min(8).max(20_000).optional(),
    tokenExpiresAt: isoDate.optional(),
    externalAccountReference: optionalText,
  }),
  z.object({
    action: z.literal("webhook.create"),
    name: shortText,
    url: z.url(),
    eventTypes: z.array(shortText).min(1).max(100),
    maxAttempts: z.coerce.number().int().min(1).max(10).default(5),
    timeoutMs: z.coerce.number().int().min(500).max(60_000).default(10_000),
  }),
  z.object({
    action: z.literal("subscription.create"),
    eventType: shortText,
    endpointId: id.optional(),
    connectorId: id.optional(),
    filters: z.record(z.string(), z.unknown()).optional(),
  }),
  z.object({
    action: z.literal("event.publish"),
    eventType: shortText,
    aggregateType: shortText,
    aggregateId: shortText,
    payload: z.record(z.string(), z.unknown()),
    correlationId: shortText.optional(),
  }),
  z.object({
    action: z.literal("connector.execute"),
    connectorId: id,
    idempotencyKey: z.string().trim().min(8).max(200),
    payload: z.record(z.string(), z.unknown()).optional(),
  }),
  z.object({
    action: z.literal("delivery.retry"),
    deliveryId: id,
  }),
]);

export const externalIntegrationEventSchema = z.object({
  eventType: shortText,
  aggregateType: shortText,
  aggregateId: shortText,
  payload: z.record(z.string(), z.unknown()),
  correlationId: shortText.optional(),
});

export const integrationWorkerSchema = z.discriminatedUnion("action", [
  z.object({
    action: z.literal("PROCESS_DELIVERIES"),
    limit: z.coerce.number().int().min(1).max(100).default(20),
  }),
  z.object({
    action: z.literal("PROCESS_RUNS"),
    limit: z.coerce.number().int().min(1).max(100).default(20),
  }),
]);
