"use client";

import { useCallback, useEffect, useState } from "react";
import { apiGet, apiMutation } from "@/lib/client/api-client";

type Capabilities = { manageJobs: boolean; manageSecurity: boolean; manageModeration: boolean; manageSupport: boolean; manageRetention: boolean; exportData: boolean };
type Summary = { readiness: { status: string; database: { status: string; latencyMs: number }; realtime: { status: string }; checkedAt: string }; queues: { byStatus: Record<string, number>; deadLetters: number }; operations: { activeWorkers: number; schedules: number; openModeration: number; openSupport: number; unresolvedHighSecurity: number; exports: Record<string, number> }; providers: Record<string, { configured?: boolean; status?: string; key?: string; latencyMs?: number }>; capabilities: Capabilities };
type Attempt = { id: string; attemptNumber: number; workerId: string; status: string; startedAt: string; completedAt: string | null; errorCode: string | null; errorMessage: string | null };
type Job = { id: string; type: string; queue: string; status: string; priority: number; attempts: number; maxAttempts: number; availableAt: string; createdAt: string; lockedBy: string | null; leaseExpiresAt: string | null; lastError: string | null; failureCode: string | null; attemptHistory: Attempt[]; deadLetter: { reason: string; failedAt: string; recoveryCount: number; resolvedAt: string | null } | null };
type Worker = { workerId: string; queues: string[]; version: string | null; hostname: string | null; observedStatus: string; currentJobId: string | null; startedAt: string; lastSeenAt: string };
type Schedule = { id: string; key: string; jobType: string; queue: string; intervalSeconds: number; enabled: boolean; nextRunAt: string; lastEnqueuedAt: string | null };
type ExportJob = { id: string; type: string; status: string; rowCount: number | null; checksumSha256: string | null; createdAt: string; expiresAt: string | null; errorMessage: string | null; artifact: { byteSize: number } | null };
type Moderation = { id: string; category: string; detail: string; resourceType: string; resourceId: string; status: string; resolution: string | null; updatedAt: string };
type Support = { id: string; number: string; subject: string; description: string; status: string; priority: string; resolution: string | null; requester: { displayName: string | null; email: string }; updatedAt: string };
type Security = { id: string; type: string; severity: string; resolvedAt: string | null; createdAt: string; metadata: unknown; user: { displayName: string | null; email: string } | null };
type Retention = { id: string; resourceType: string; retentionDays: number; legalHoldDefault: boolean; updatedAt: string };
type Tab = "overview" | "jobs" | "workers" | "exports" | "moderation" | "support" | "security" | "retention";

const field = "rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm";
const primary = "rounded-full bg-[#009A44] px-4 py-2 text-sm font-bold text-white disabled:opacity-50";
const secondary = "rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-[#0F4C5C] disabled:opacity-50";
const card = "rounded-3xl border border-slate-200 bg-white p-5";
function message(reason: unknown, fallback: string) { return reason instanceof Error ? reason.message : fallback; }
function time(value?: string | null) { return value ? new Intl.DateTimeFormat("en-AE", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Dubai" }).format(new Date(value)) : "Never"; }
function tone(status: string) { return ["COMPLETED", "RESOLVED", "CLOSED", "healthy", "ready", "ACTIVE"].includes(status) ? "bg-emerald-50 text-emerald-700" : ["FAILED", "DEAD_LETTER", "CRITICAL", "HIGH", "unhealthy"].includes(status) ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"; }

export function EnterpriseOperationsClient({ capabilities, initialTab = "overview" }: { capabilities: Capabilities; initialTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(initialTab);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [workers, setWorkers] = useState<Worker[]>([]);
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [exports, setExports] = useState<ExportJob[]>([]);
  const [moderation, setModeration] = useState<Moderation[]>([]);
  const [support, setSupport] = useState<Support[]>([]);
  const [security, setSecurity] = useState<Security[]>([]);
  const [retention, setRetention] = useState<Retention[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [nextSummary, nextJobs, nextWorkers, nextSchedules] = await Promise.all([apiGet<Summary>("/api/operations/summary"), apiGet<{ items: Job[] }>("/api/operations/jobs?take=100"), apiGet<Worker[]>("/api/operations/workers"), apiGet<Schedule[]>("/api/operations/schedules")]);
      setSummary(nextSummary); setJobs(nextJobs.items); setWorkers(nextWorkers); setSchedules(nextSchedules);
      if (capabilities.exportData) setExports((await apiGet<{ items: ExportJob[] }>("/api/admin/data-exports?take=100")).items);
      if (capabilities.manageModeration) setModeration(await apiGet<Moderation[]>("/api/admin/moderation"));
      if (capabilities.manageSupport) setSupport(await apiGet<Support[]>("/api/admin/support-cases"));
      if (capabilities.manageSecurity) setSecurity(await apiGet<Security[]>("/api/admin/security-events"));
      if (capabilities.manageRetention) setRetention(await apiGet<Retention[]>("/api/compliance/retention"));
    } catch (reason) { setError(message(reason, "Unable to load enterprise operations.")); }
    finally { setLoading(false); }
  }, [capabilities]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);

  async function mutate(key: string, work: () => Promise<unknown>, success: string) {
    setBusy(key); setError(""); setNotice("");
    try { await work(); setNotice(success); await load(); }
    catch (reason) { setError(message(reason, "The operations command failed.")); }
    finally { setBusy(""); }
  }

  async function createSchedule(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    await mutate("schedule", () => apiMutation("/api/operations/schedules", "POST", { key: form.get("key"), jobType: form.get("jobType"), queue: "operations", payload: {}, intervalSeconds: Number(form.get("intervalSeconds")), priority: 100, maxAttempts: 10, enabled: true, nextRunAt: new Date().toISOString() }), "Recurring schedule created.");
  }

  async function requestExport(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    await mutate("export", () => apiMutation("/api/admin/data-exports", "POST", { type: form.get("type"), filters: {} }), "Export request queued for background processing.");
  }

  async function createSupport(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    await mutate("support-create", () => apiMutation("/api/admin/support-cases", "POST", { subject: form.get("subject"), description: form.get("description"), priority: form.get("priority") }), "Support case created.");
  }

  async function saveRetention(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    await mutate("retention", () => apiMutation("/api/compliance/retention", "PUT", { resourceType: form.get("resourceType"), retentionDays: Number(form.get("retentionDays")), legalHoldDefault: form.get("legalHoldDefault") === "on", configuration: {} }), "Retention policy saved with audit evidence.");
  }

  const visibleTabs: Array<[Tab, string, boolean]> = [["overview", "Overview", true], ["jobs", "Background jobs", true], ["workers", "Workers & schedules", true], ["exports", "Exports", capabilities.exportData], ["moderation", "Moderation", capabilities.manageModeration], ["support", "Support", capabilities.manageSupport], ["security", "Security", capabilities.manageSecurity], ["retention", "Retention", capabilities.manageRetention]];
  return <main className="py-12 lg:py-16">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold uppercase tracking-[.18em] text-[#009A44]">Enterprise control plane</p><h1 className="text-4xl font-bold text-[#0F4C5C]">Administration & operations</h1><p className="mt-2 max-w-3xl text-slate-600">Live health, background processing, dead-letter recovery and governed operational queues for the active organization.</p></div><button className={secondary} disabled={loading} onClick={() => void load()}>{loading ? "Refreshing…" : "Refresh"}</button></header>
    {error ? <div role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</div> : null}{notice ? <div role="status" className="mt-5 rounded-xl bg-emerald-50 p-4 text-emerald-700">{notice}</div> : null}
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[["Readiness", summary?.readiness.status ?? "Unknown"], ["Active workers", summary?.operations.activeWorkers ?? 0], ["Pending jobs", summary?.queues.byStatus.PENDING ?? 0], ["Dead letters", summary?.queues.deadLetters ?? 0], ["Open support", summary?.operations.openSupport ?? 0], ["High security", summary?.operations.unresolvedHighSecurity ?? 0]].map(([label, value]) => <article key={label} className={card}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-[#0F4C5C]">{value}</p></article>)}</section>
    <nav className="mt-7 flex gap-2 overflow-x-auto pb-2">{visibleTabs.filter((item) => item[2]).map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab === key ? "bg-[#0F4C5C] text-white" : "border border-slate-300 bg-white text-[#0F4C5C]"}`}>{label}</button>)}</nav>

    {tab === "overview" ? <section className="mt-5 grid gap-5 lg:grid-cols-2"><article className={card}><h2 className="text-xl font-bold text-[#0F4C5C]">Runtime health</h2><dl className="mt-4 grid gap-3 text-sm">{[["Database", `${summary?.readiness.database.status ?? "unknown"} · ${summary?.readiness.database.latencyMs ?? 0} ms`], ["Realtime", summary?.readiness.realtime.status ?? "unknown"], ["Checked", time(summary?.readiness.checkedAt)], ["Recurring schedules", summary?.operations.schedules ?? 0], ["Open moderation", summary?.operations.openModeration ?? 0]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b py-2"><dt className="font-bold text-slate-500">{label}</dt><dd>{value}</dd></div>)}</dl></article><article className={card}><h2 className="text-xl font-bold text-[#0F4C5C]">Provider status</h2><div className="mt-4 grid gap-3">{Object.entries(summary?.providers ?? {}).map(([name, status]) => <div key={name} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><strong className="capitalize">{name}</strong><span className={`rounded-full px-3 py-1 text-xs font-bold ${tone(status.status ?? (status.configured ? "healthy" : "unhealthy"))}`}>{status.status ?? (status.configured ? "configured" : "not configured")}</span></div>)}</div></article></section> : null}

    {tab === "jobs" ? <section className="mt-5 grid gap-3">{jobs.map((job) => <article key={job.id} className={card}><div className="flex flex-wrap justify-between gap-4"><div><span className={`rounded-full px-2 py-1 text-xs font-bold ${tone(job.status)}`}>{job.status}</span><h3 className="mt-2 text-lg font-bold text-[#0F4C5C]">{job.type}</h3><p className="text-sm text-slate-500">{job.queue} · attempts {job.attempts}/{job.maxAttempts} · {job.id.slice(0, 12)} · created {time(job.createdAt)}</p>{job.lastError ? <p className="mt-2 max-w-3xl text-sm text-red-600">{job.failureCode}: {job.lastError}</p> : null}</div>{capabilities.manageJobs ? <div className="flex h-fit gap-2">{["PENDING", "PROCESSING"].includes(job.status) ? <button className={secondary} onClick={() => void mutate(`cancel:${job.id}`, () => apiMutation(`/api/operations/jobs/${job.id}/cancel`, "POST", { reason: "Cancelled from worker dashboard." }), "Job cancelled.")}>Cancel</button> : null}{["FAILED", "CANCELLED"].includes(job.status) ? <button className={secondary} onClick={() => void mutate(`retry:${job.id}`, () => apiMutation(`/api/operations/jobs/${job.id}/retry`, "POST", { reason: "Controlled operator retry." }), "Job requeued.")}>Retry</button> : null}{job.status === "DEAD_LETTER" ? <button className={primary} onClick={() => void mutate(`recover:${job.id}`, () => apiMutation(`/api/operations/jobs/${job.id}/recover`, "POST", { reason: "Diagnostics reviewed; controlled recovery." }), "Dead-letter job recovered for replay.")}>Recover</button> : null}</div> : null}</div><details className="mt-3"><summary className="cursor-pointer text-sm font-bold">Attempt history ({job.attemptHistory.length})</summary><div className="mt-2 grid gap-2">{job.attemptHistory.map((attempt) => <div key={attempt.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>#{attempt.attemptNumber} · {attempt.status}</strong> · {attempt.workerId} · {time(attempt.startedAt)}{attempt.errorMessage ? <p className="text-red-600">{attempt.errorCode}: {attempt.errorMessage}</p> : null}</div>)}</div></details></article>)}</section> : null}

    {tab === "workers" ? <section className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="grid gap-3">{workers.map((worker) => <article key={worker.workerId} className={card}><div className="flex justify-between"><div><h3 className="font-bold text-[#0F4C5C]">{worker.workerId}</h3><p className="text-sm text-slate-500">{worker.hostname ?? "Unknown host"} · {worker.version ?? "Unknown version"}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${tone(worker.observedStatus)}`}>{worker.observedStatus}</span></div><p className="mt-3 text-sm">Queues: {worker.queues.join(", ") || "none"} · last seen {time(worker.lastSeenAt)} · job {worker.currentJobId?.slice(0, 12) ?? "idle"}</p></article>)}<h2 className="mt-3 text-xl font-bold text-[#0F4C5C]">Schedules</h2>{schedules.map((schedule) => <article key={schedule.id} className={card}><strong>{schedule.jobType}</strong><p className="text-sm text-slate-500">{schedule.key} · every {schedule.intervalSeconds}s · next {time(schedule.nextRunAt)}</p>{capabilities.manageJobs ? <button className={`${secondary} mt-3`} onClick={() => void mutate(`schedule:${schedule.id}`, () => apiMutation(`/api/operations/schedules/${schedule.id}`, "PATCH", { enabled: !schedule.enabled }), schedule.enabled ? "Schedule paused." : "Schedule enabled.")}>{schedule.enabled ? "Pause" : "Enable"}</button> : null}</article>)}</div>{capabilities.manageJobs ? <form onSubmit={(event) => void createSchedule(event)} className={`${card} grid h-fit gap-3`}><h2 className="text-xl font-bold text-[#0F4C5C]">New schedule</h2><input className={field} name="key" placeholder="daily-retention" required/><select className={field} name="jobType"><option>RETENTION_ENFORCE</option><option>SEARCH_INCREMENTAL</option><option>NOTIFICATION_DELIVERY</option></select><input className={field} type="number" min="60" name="intervalSeconds" defaultValue="86400" required/><button className={primary}>Create schedule</button></form> : null}</section> : null}

    {tab === "exports" ? <section className="mt-5 grid gap-5 lg:grid-cols-[320px_minmax(0,1fr)]"><form onSubmit={(event) => void requestExport(event)} className={`${card} grid h-fit gap-3`}><h2 className="text-xl font-bold text-[#0F4C5C]">Request export</h2><select className={field} name="type"><option>ORGANIZATION</option><option>PROJECT</option><option>FINANCE</option><option>AUDIT</option></select><button className={primary}>Queue export</button></form><div className="grid gap-3">{exports.map((item) => <article key={item.id} className={card}><div className="flex justify-between"><div><strong>{item.type}</strong><p className="text-sm text-slate-500">{item.rowCount ?? 0} records · {item.artifact?.byteSize ?? 0} bytes · {time(item.createdAt)}</p>{item.errorMessage ? <p className="text-sm text-red-600">{item.errorMessage}</p> : null}</div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${tone(item.status)}`}>{item.status}</span></div>{item.status === "COMPLETED" ? <a className={`${secondary} mt-3 inline-block`} href={`/api/admin/data-exports/${item.id}/download`}>Download verified JSON</a> : null}</article>)}</div></section> : null}

    {tab === "moderation" ? <section className="mt-5 grid gap-3">{moderation.map((item) => <article key={item.id} className={card}><div className="flex flex-wrap justify-between gap-3"><div><strong>{item.category} · {item.resourceType}</strong><p className="text-sm text-slate-600">{item.detail}</p><p className="text-xs text-slate-500">{item.resourceId} · {time(item.updatedAt)}</p></div><div className="flex gap-2"><button className={secondary} onClick={() => void mutate(`investigate:${item.id}`, () => apiMutation("/api/admin/moderation", "PATCH", { reportId: item.id, status: "INVESTIGATING", resolution: "Investigation opened from moderation queue." }), "Report moved to investigation.")}>Investigate</button><button className={primary} onClick={() => void mutate(`action:${item.id}`, () => apiMutation("/api/admin/moderation", "PATCH", { reportId: item.id, status: "ACTIONED", resolution: "Governed moderation action completed." }), "Moderation action recorded.")}>Action</button></div></div></article>)}</section> : null}

    {tab === "support" ? <section className="mt-5 grid gap-5 lg:grid-cols-[320px_minmax(0,1fr)]"><form onSubmit={(event) => void createSupport(event)} className={`${card} grid h-fit gap-3`}><h2 className="text-xl font-bold text-[#0F4C5C]">Create case</h2><input className={field} name="subject" placeholder="Subject" required/><textarea className={field} name="description" rows={4} placeholder="Describe the issue" required/><select className={field} name="priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select><button className={primary}>Create support case</button></form><div className="grid gap-3">{support.map((item) => <article key={item.id} className={card}><div className="flex justify-between"><div><strong>{item.number} · {item.subject}</strong><p className="text-sm text-slate-600">{item.description}</p><p className="text-xs text-slate-500">{item.requester.displayName ?? item.requester.email} · {time(item.updatedAt)}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${tone(item.status)}`}>{item.priority} · {item.status}</span></div><div className="mt-3 flex gap-2"><button className={secondary} onClick={() => void mutate(`support:${item.id}`, () => apiMutation(`/api/admin/support-cases/${item.id}`, "PATCH", { status: "IN_PROGRESS" }), "Support case accepted.")}>Accept</button><button className={primary} onClick={() => void mutate(`resolve:${item.id}`, () => apiMutation(`/api/admin/support-cases/${item.id}`, "PATCH", { status: "RESOLVED", resolution: "Resolved through enterprise support operations." }), "Support case resolved.")}>Resolve</button></div></article>)}</div></section> : null}

    {tab === "security" ? <section className="mt-5 grid gap-3">{security.map((item) => <article key={item.id} className={card}><div className="flex flex-wrap justify-between gap-4"><div><span className={`rounded-full px-3 py-1 text-xs font-bold ${tone(item.severity)}`}>{item.severity}</span><h3 className="mt-2 font-bold text-[#0F4C5C]">{item.type}</h3><p className="text-sm text-slate-500">{item.user?.displayName ?? item.user?.email ?? "System"} · {time(item.createdAt)}</p></div><button className={secondary} onClick={() => void mutate(`security:${item.id}`, () => apiMutation(`/api/admin/security-events/${item.id}`, "PATCH", { resolved: !item.resolvedAt, note: item.resolvedAt ? "Reopened for further investigation." : "Reviewed and resolved in security queue." }), item.resolvedAt ? "Security event reopened." : "Security event resolved.")}>{item.resolvedAt ? "Reopen" : "Resolve"}</button></div></article>)}</section> : null}

    {tab === "retention" ? <section className="mt-5 grid gap-5 lg:grid-cols-[320px_minmax(0,1fr)]"><form onSubmit={(event) => void saveRetention(event)} className={`${card} grid h-fit gap-3`}><h2 className="text-xl font-bold text-[#0F4C5C]">Retention policy</h2><input className={field} name="resourceType" placeholder="DATA_EXPORT" required/><input className={field} type="number" min="1" max="36500" name="retentionDays" defaultValue="30" required/><label className="text-sm font-bold"><input type="checkbox" name="legalHoldDefault"/> Legal hold by default</label><button className={primary}>Save policy</button></form><div className="grid gap-3">{retention.map((item) => <article key={item.id} className={card}><div className="flex justify-between"><div><strong>{item.resourceType}</strong><p className="text-sm text-slate-500">{item.retentionDays} days · updated {time(item.updatedAt)}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.legalHoldDefault ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{item.legalHoldDefault ? "Legal hold default" : "Standard retention"}</span></div></article>)}</div></section> : null}
  </main>;
}
