import { createHash,randomBytes } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/database/prisma";
import { AppError } from "@/lib/errors/app-error";
import { requirePermission } from "@/lib/authorization/permission-resolver";
import type { TenantContext } from "@/lib/tenancy/context";
const json=(v:unknown)=>JSON.parse(JSON.stringify(v)) as Prisma.InputJsonValue;

export class MarketplaceLifecycleService{
 async get(context:TenantContext,id:string){await requirePermission(context,"marketplace.listing.read");const row=await prisma.marketplaceListing.findFirst({where:{id,OR:[{organizationId:context.organizationId},{status:"PUBLISHED",visibility:"PUBLIC"}]},include:{organization:{select:{id:true,name:true,slug:true}},skills:{include:{skill:true}},proposals:{where:{submittedById:context.userId},orderBy:{updatedAt:"desc"}},_count:{select:{proposals:true,savedBy:true}}}});if(!row)throw new AppError("NOT_FOUND","Listing not found.",404);return row;}
 async update(context:TenantContext,id:string,input:Record<string,unknown>){await requirePermission(context,"marketplace.listing.manage");const row=await prisma.marketplaceListing.findFirst({where:{id,organizationId:context.organizationId}});if(!row)throw new AppError("NOT_FOUND","Listing not found.",404);return prisma.marketplaceListing.update({where:{id},data:{...input,publishedAt:input.status==="PUBLISHED"?(row.publishedAt??new Date()):undefined,closedAt:input.status==="CLOSED"?new Date():undefined} as Prisma.MarketplaceListingUpdateInput});}
 async save(context:TenantContext,id:string,active:boolean){await this.get(context,id);if(active){await prisma.savedListing.upsert({where:{userId_listingId:{userId:context.userId,listingId:id}},create:{userId:context.userId,listingId:id},update:{}});}else await prisma.savedListing.deleteMany({where:{userId:context.userId,listingId:id}});return{saved:active};}
}

export class ContractLifecycleService{
 private async access(context:TenantContext,id:string){const row=await prisma.contract.findFirst({where:{id,OR:[{organizationId:context.organizationId},{providerOrganizationId:context.organizationId},{providerUserId:context.userId}]},include:{amendments:true,milestones:{include:{submissions:true}},invoices:true,transactions:true,disputes:true,reviews:true,project:true,listing:true}});if(!row)throw new AppError("NOT_FOUND","Contract not found.",404);return row;}
 async get(context:TenantContext,id:string){await requirePermission(context,"marketplace.contract.manage");return this.access(context,id);}
 async transition(context:TenantContext,id:string,status:string){await requirePermission(context,"marketplace.contract.manage");const row=await this.access(context,id);const allowed:Record<string,string[]>={DRAFT:["PENDING_SIGNATURES","TERMINATED"],PENDING_SIGNATURES:["ACTIVE","TERMINATED"],ACTIVE:["PAUSED","COMPLETED","TERMINATED","DISPUTED"],PAUSED:["ACTIVE","TERMINATED","DISPUTED"],DISPUTED:["ACTIVE","TERMINATED"]};if(!(allowed[row.status]??[]).includes(status))throw new AppError("CONFLICT",`Invalid contract transition from ${row.status} to ${status}.`,409);return prisma.contract.update({where:{id},data:{status:status as never,signedAt:status==="ACTIVE"?(row.signedAt??new Date()):undefined,completedAt:status==="COMPLETED"?new Date():undefined}});}
 async amendment(context:TenantContext,id:string,input:{summary:string;changes:Record<string,unknown>;submit:boolean}){await requirePermission(context,"marketplace.contract.manage");await this.access(context,id);const last=await prisma.contractAmendment.aggregate({where:{contractId:id},_max:{version:true}});return prisma.contractAmendment.create({data:{contractId:id,proposedById:context.userId,version:(last._max.version??0)+1,summary:input.summary,changes:json(input.changes),status:input.submit?"PROPOSED":"DRAFT"}});}
 async milestone(context:TenantContext,id:string,input:{title:string;description?:string;amountMinor:bigint;currency:string;dueAt?:Date}){await requirePermission(context,"marketplace.contract.manage");await this.access(context,id);return prisma.contractMilestone.create({data:{contractId:id,...input}});}
 async dispute(context:TenantContext,id:string,input:{category:string;reason:string;againstUserId?:string;evidence?:Record<string,unknown>}){await this.access(context,id);return prisma.$transaction(async tx=>{const dispute=await tx.dispute.create({data:{contractId:id,openedById:context.userId,againstUserId:input.againstUserId,category:input.category,reason:input.reason,evidence:input.evidence?json(input.evidence):undefined}});await tx.contract.update({where:{id},data:{status:"DISPUTED"}});return dispute;});}
}

export class FileLifecycleService{
 private async file(context:TenantContext,id:string){const row=await prisma.fileNode.findFirst({where:{id,organizationId:context.organizationId},include:{versions:{orderBy:{version:"desc"}},lock:{include:{lockedBy:{select:{id:true,displayName:true}}}},accessGrants:true,activities:{orderBy:{createdAt:"desc"},take:100}}});if(!row)throw new AppError("NOT_FOUND","File not found.",404);return row;}
 async get(context:TenantContext,id:string){await requirePermission(context,"files.read");return this.file(context,id);}
 async update(context:TenantContext,id:string,input:{name?:string;retentionUntil?:Date|null;legalHold?:boolean;deleted?:boolean}){await requirePermission(context,"files.manage");const file=await this.file(context,id);if(input.deleted&&file.legalHold)throw new AppError("CONFLICT","A file under legal hold cannot be deleted.",409);const updated=await prisma.fileNode.update({where:{id},data:{name:input.name,retentionUntil:input.retentionUntil,legalHold:input.legalHold,deletedAt:input.deleted===true?new Date():input.deleted===false?null:undefined}});await prisma.fileActivity.create({data:{fileNodeId:id,actorUserId:context.userId,type:input.legalHold!==undefined?"LEGAL_HOLD_CHANGED":input.deleted===true?"DELETED":input.deleted===false?"RESTORED":"RENAMED",metadata:json({fields:Object.keys(input)})}});return updated;}
 async versions(context:TenantContext,id:string){await requirePermission(context,"files.read");return (await this.file(context,id)).versions;}
 async lock(context:TenantContext,id:string,minutes:number){await requirePermission(context,"files.manage");await this.file(context,id);const raw=randomBytes(32).toString("base64url");const tokenHash=createHash("sha256").update(raw).digest("hex");const lock=await prisma.fileLock.upsert({where:{fileNodeId:id},create:{fileNodeId:id,lockedById:context.userId,tokenHash,expiresAt:new Date(Date.now()+minutes*60000)},update:{lockedById:context.userId,tokenHash,expiresAt:new Date(Date.now()+minutes*60000)}});return{lock,lockToken:raw};}
 async unlock(context:TenantContext,id:string){await requirePermission(context,"files.manage");await this.file(context,id);await prisma.fileLock.deleteMany({where:{fileNodeId:id,OR:[{lockedById:context.userId},{expiresAt:{lte:new Date()}}]}});return{unlocked:true};}
}

export class BillingAdministrationService{
 async summary(context:TenantContext){await requirePermission(context,"finance.read");const[subscription,usage,credits,invoices,transactions]=await Promise.all([prisma.organizationSubscription.findUnique({where:{organizationId:context.organizationId},include:{plan:true}}),prisma.usageRecord.groupBy({by:["unit"],where:{organizationId:context.organizationId},_sum:{quantity:true}}),prisma.creditLedgerEntry.aggregate({where:{organizationId:context.organizationId},_sum:{amountMinor:true}}),prisma.invoice.groupBy({by:["status"],where:{organizationId:context.organizationId},_count:true,_sum:{totalMinor:true}}),prisma.financialTransaction.groupBy({by:["status"],where:{organizationId:context.organizationId},_count:true,_sum:{amountMinor:true}})]);return{subscription,usage,creditBalanceMinor:credits._sum.amountMinor??0,invoices,transactions,currency:"AED"};}
 async configure(context:TenantContext,input:{planId:string;status:"TRIALING"|"ACTIVE"|"PAST_DUE"|"PAUSED"|"CANCELLED"|"EXPIRED";currentPeriodEnd:Date;cancelAtPeriodEnd:boolean}){await requirePermission(context,"billing.manage");const plan=await prisma.subscriptionPlan.findFirst({where:{id:input.planId,isActive:true}});if(!plan)throw new AppError("NOT_FOUND","Subscription plan not found.",404);return prisma.organizationSubscription.upsert({where:{organizationId:context.organizationId},create:{organizationId:context.organizationId,planId:input.planId,status:input.status,currentPeriodStart:new Date(),currentPeriodEnd:input.currentPeriodEnd,cancelAtPeriodEnd:input.cancelAtPeriodEnd},update:{planId:input.planId,status:input.status,currentPeriodEnd:input.currentPeriodEnd,cancelAtPeriodEnd:input.cancelAtPeriodEnd}});}
}

export class ModerationComplianceService{
 async queue(context:TenantContext){await requirePermission(context,"moderation.manage");return prisma.abuseReport.findMany({where:{organizationId:context.organizationId},orderBy:{updatedAt:"desc"},take:100});}
 async decide(context:TenantContext,input:{reportId:string;status:"TRIAGED"|"INVESTIGATING"|"ACTIONED"|"DISMISSED";resolution:string}){await requirePermission(context,"moderation.manage");const updated=await prisma.abuseReport.updateMany({where:{id:input.reportId,organizationId:context.organizationId},data:{status:input.status,resolution:input.resolution,assignedToId:context.userId}});if(!updated.count)throw new AppError("NOT_FOUND","Abuse report not found.",404);return prisma.abuseReport.findUnique({where:{id:input.reportId}});}
 async retention(context:TenantContext,input?:{resourceType:string;retentionDays:number;legalHoldDefault:boolean;configuration?:Record<string,unknown>}){if(!input){await requirePermission(context,"compliance.manage");return prisma.dataRetentionPolicy.findMany({where:{organizationId:context.organizationId}});}await requirePermission(context,"compliance.manage");return prisma.dataRetentionPolicy.upsert({where:{organizationId_resourceType:{organizationId:context.organizationId,resourceType:input.resourceType}},create:{organizationId:context.organizationId,resourceType:input.resourceType,retentionDays:input.retentionDays,legalHoldDefault:input.legalHoldDefault,configuration:input.configuration?json(input.configuration):undefined},update:{retentionDays:input.retentionDays,legalHoldDefault:input.legalHoldDefault,configuration:input.configuration?json(input.configuration):undefined}});}
}
