import type { PlatformPermission } from "@/lib/authorization/permissions";

export const DEFAULT_ROLES: Array<{
  name: string;
  description: string;
  permissions: PlatformPermission[];
}> = [
  {
    name: "Owner",
    description: "Full organization control.",
    permissions: [
      "organization.read",
      "organization.update",
      "organization.settings.manage",
      "organization.members.read",
      "organization.members.manage",
      "organization.roles.read",
      "organization.roles.manage",
      "organization.invitations.manage",
      "project.read",
      "project.create",
      "project.update",
      "project.delete",
      "chat.read",
      "chat.channel.create",
      "chat.message.create",
      "chat.moderate",
      "marketplace.profile.manage",
      "marketplace.listing.read",
      "marketplace.listing.manage",
      "marketplace.proposal.manage",
      "marketplace.proposal.review",
      "marketplace.contract.manage",
      "workspace.delivery.manage",
      "files.read",
      "files.manage",
      "ai.use",
      "ai.manage",
      "finance.read",
      "finance.manage",
      "analytics.read",
      "search.use",
      "support.manage",
      "security.events.read",
      "data.export",
      "orchestration.read", "orchestration.manage", "orchestration.run", "orchestration.approve",
      "workgraph.read", "workgraph.manage", "matching.manage", "billing.manage",
      "moderation.manage", "compliance.manage", "platform.operations.read",
      "audit.read",
    ],
  },
  {
    name: "Admin",
    description: "Administrative workspace control.",
    permissions: [
      "organization.read",
      "organization.update",
      "organization.settings.manage",
      "organization.members.read",
      "organization.members.manage",
      "organization.roles.read",
      "organization.roles.manage",
      "organization.invitations.manage",
      "project.read",
      "project.create",
      "project.update",
      "project.delete",
      "chat.read",
      "chat.channel.create",
      "chat.message.create",
      "chat.moderate",
      "marketplace.profile.manage",
      "marketplace.listing.read",
      "marketplace.listing.manage",
      "marketplace.proposal.manage",
      "marketplace.proposal.review",
      "marketplace.contract.manage",
      "workspace.delivery.manage",
      "files.read",
      "files.manage",
      "ai.use",
      "ai.manage",
      "finance.read",
      "finance.manage",
      "analytics.read",
      "search.use",
      "support.manage",
      "security.events.read",
      "data.export",
      "orchestration.read", "orchestration.manage", "orchestration.run", "orchestration.approve",
      "workgraph.read", "workgraph.manage", "matching.manage", "billing.manage",
      "moderation.manage", "compliance.manage", "platform.operations.read",
      "audit.read",
    ],
  },
  {
    name: "Manager",
    description: "Operational management access.",
    permissions: [
      "organization.read",
      "organization.members.read",
      "organization.roles.read",
      "project.read",
      "project.create",
      "project.update",
      "chat.read",
      "chat.channel.create",
      "chat.message.create",
      "chat.moderate",
      "marketplace.profile.manage",
      "marketplace.listing.read",
      "marketplace.listing.manage",
      "marketplace.proposal.manage",
      "marketplace.proposal.review",
      "marketplace.contract.manage",
      "workspace.delivery.manage",
      "files.read",
      "files.manage",
      "ai.use",
      "finance.read",
      "finance.manage",
      "analytics.read",
      "search.use",
      "data.export",
      "orchestration.read", "orchestration.run", "orchestration.approve",
      "workgraph.read", "matching.manage", "billing.manage", "moderation.manage",
      "platform.operations.read",
    ],
  },
  {
    name: "Member",
    description: "Standard contributor access.",
    permissions: [
      "organization.read",
      "organization.members.read",
      "project.read",
      "project.create",
      "project.update",
      "chat.read",
      "chat.channel.create",
      "chat.message.create",
      "marketplace.profile.manage",
      "marketplace.listing.read",
      "marketplace.proposal.manage",
      "workspace.delivery.manage",
      "files.read",
      "files.manage",
      "ai.use",
      "finance.read",
      "analytics.read",
      "search.use",
      "orchestration.read", "orchestration.run", "workgraph.read",
    ],
  },
  {
    name: "Viewer",
    description: "Read-only access.",
    permissions: [
      "organization.read",
      "organization.members.read",
      "project.read",
      "chat.read",
      "marketplace.listing.read",
      "files.read",
      "finance.read",
      "analytics.read",
      "search.use",
      "orchestration.read", "workgraph.read",
    ],
  },
];
