"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Button, Card, Badge } from "@/components/ui";
import { brand } from "@/constants/design";
async function csrf(){const r=await fetch("/api/auth/csrf",{cache:"no-store"});const b=await r.json();return b.data?.csrfToken as string;}
export default function LoginForm(){const t=useTranslations("Auth");const router=useRouter();const [pending,setPending]=useState(false);const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setError("");const data=new FormData(e.currentTarget);try{const token=await csrf();const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json","x-csrf-token":token},body:JSON.stringify({email:data.get("email"),password:data.get("password")})});const b=await r.json();if(!r.ok)throw new Error(b.error?.message??t("requestFailed"));router.push("/platform");router.refresh();}catch(x){setError(x instanceof Error?x.message:t("requestFailed"));}finally{setPending(false);}}return <Card variant="elevated" style={{width:"100%",maxWidth:480}}><Badge variant="success">{t("welcomeBack")}</Badge><h1 style={{color:brand.colors.navy,fontSize:brand.typography.heading.h3,marginTop:24}}>{t("loginTitle")}</h1><p style={{color:brand.colors.muted}}>{t("loginDescription")}</p><form className="auth-form" onSubmit={submit}><label>{t("email")}<input name="email" type="email" autoComplete="email" required /></label><label>{t("password")}<input name="password" type="password" autoComplete="current-password" required /></label>{error?<p className="enterprise-error" role="alert">{error}</p>:null}<Button variant="primary" type="submit" disabled={pending}>{pending?t("signingIn"):t("signIn")}</Button></form><p><Link href="/forgot-password">{t("forgotPassword")}</Link></p><p>{t("noAccount")} <Link href="/register">{t("createAccount")}</Link></p></Card>}
